"""
MULTI-LANGUAGE BACKEND GENERATOR
Supports: Python, Go, Rust, Java, C#, PHP backends
"""

import json
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

@dataclass
class BackendLanguageConfig:
    """Configuration for multi-language backend generation"""
    project_id: str
    project_name: str
    language: str  # "python", "go", "rust", "java", "csharp", "php"
    framework: str  # language-specific
    version: str = "1.0.0"
    database: str = "postgresql"  # postgresql, mongodb, mysql


class MultiLanguageBackendGenerator:
    """Generates backend APIs in multiple programming languages"""
    
    SUPPORTED_LANGUAGES = ["python", "go", "rust", "java", "csharp", "php"]
    
    def generate(self, config: BackendLanguageConfig, blueprint: Dict[str, Any]) -> Dict[str, str]:
        """Generate backend for specified language"""
        
        if config.language == "python":
            return self._generate_python(config, blueprint)
        elif config.language == "go":
            return self._generate_go(config, blueprint)
        elif config.language == "rust":
            return self._generate_rust(config, blueprint)
        elif config.language == "java":
            return self._generate_java(config, blueprint)
        elif config.language == "csharp":
            return self._generate_csharp(config, blueprint)
        elif config.language == "php":
            return self._generate_php(config, blueprint)
        else:
            raise ValueError(f"Unsupported language: {config.language}")
    
    # ============== PYTHON (FastAPI) ==============
    
    def _generate_python(self, config: BackendLanguageConfig, blueprint: Dict[str, Any]) -> Dict[str, str]:
        """Generate FastAPI Python backend"""
        files = {}
        
        files["requirements.txt"] = self._template_python_requirements(config)
        files["app/main.py"] = self._template_python_main(config)
        files["app/config.py"] = self._template_python_config(config)
        files["app/models.py"] = self._template_python_models(blueprint)
        files["app/schemas.py"] = self._template_python_schemas(blueprint)
        files["app/database.py"] = self._template_python_database(config)
        files["app/routers/__init__.py"] = ""
        files["app/routers/auth.py"] = self._template_python_auth_router()
        files["app/routers/items.py"] = self._template_python_items_router()
        files["app/routers/users.py"] = self._template_python_users_router()
        files["app/middleware.py"] = self._template_python_middleware()
        files["Dockerfile"] = self._template_python_dockerfile(config)
        files[".dockerignore"] = "*.pyc\n__pycache__\n.venv\n.env"
        files["docker-compose.yml"] = self._template_python_docker_compose(config)
        files[".env.example"] = self._template_python_env_example()
        files["pytest.ini"] = self._template_pytest_ini()
        files["tests/__init__.py"] = ""
        files["tests/test_main.py"] = self._template_python_tests()
        
        return files
    
    def _template_python_requirements(self, config: BackendLanguageConfig) -> str:
        return """fastapi==0.104.0
uvicorn[standard]==0.24.0
pydantic==2.5.0
pydantic-settings==2.1.0
sqlalchemy==2.0.0
psycopg2-binary==2.9.0
pymongo==4.6.0
python-jose[cryptography]==3.3.0
passlib[bcrypt]==1.7.4
python-multipart==0.0.6
pytest==7.4.0
pytest-asyncio==0.21.0
httpx==0.25.0
python-dotenv==1.0.0
alembic==1.12.0
"""
    
    def _template_python_main(self, config: BackendLanguageConfig) -> str:
        return f"""from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.config import settings
from app.routers import auth, items, users
from app.middleware import timing_middleware

app = FastAPI(
    title="{config.project_name}",
    version="{config.version}",
    description="API generated by GAAIUS"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Custom middleware
app.add_middleware(timing_middleware)

# Include routers
app.include_router(auth.router, prefix="/api/auth", tags=["auth"])
app.include_router(items.router, prefix="/api/items", tags=["items"])
app.include_router(users.router, prefix="/api/users", tags=["users"])

@app.get("/")
async def root():
    return {{"message": "Welcome to {config.project_name}", "version": "{config.version}"}}

@app.get("/health")
async def health():
    return {{"status": "ok"}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
"""
    
    def _template_python_config(self, config: BackendLanguageConfig) -> str:
        return """from pydantic_settings import BaseSettings
from typing import List

class Settings(BaseSettings):
    DATABASE_URL: str = "postgresql://user:password@localhost/dbname"
    SECRET_KEY: str = "your-secret-key-here"
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    ALLOWED_ORIGINS: List[str] = ["http://localhost:5173", "http://localhost:3000"]
    
    class Config:
        env_file = ".env"

settings = Settings()
"""
    
    def _template_python_models(self, blueprint: Dict[str, Any]) -> str:
        return """from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    username = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class Item(Base):
    __tablename__ = "items"
    
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(Text)
    owner_id = Column(Integer)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
"""
    
    def _template_python_schemas(self, blueprint: Dict[str, Any]) -> str:
        return """from pydantic import BaseModel, EmailStr
from datetime import datetime
from typing import Optional

class UserBase(BaseModel):
    email: EmailStr
    username: str

class UserCreate(UserBase):
    password: str

class User(UserBase):
    id: int
    is_active: bool
    created_at: datetime
    
    class Config:
        from_attributes = True

class ItemBase(BaseModel):
    title: str
    description: Optional[str] = None

class ItemCreate(ItemBase):
    pass

class Item(ItemBase):
    id: int
    owner_id: int
    created_at: datetime
    
    class Config:
        from_attributes = True

class Token(BaseModel):
    access_token: str
    token_type: str
"""
    
    def _template_python_database(self, config: BackendLanguageConfig) -> str:
        return """from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.config import settings

engine = create_engine(settings.DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
"""
    
    def _template_python_auth_router(self) -> str:
        return """from fastapi import APIRouter, Depends, HTTPException, status
from app.schemas import UserCreate, User, Token
from app.models import User as UserModel
from sqlalchemy.orm import Session
from app.database import get_db
from app.config import settings
from datetime import datetime, timedelta
from jose import JWTError, jwt
from passlib.context import CryptContext

router = APIRouter()
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

@router.post("/register", response_model=User)
async def register(user: UserCreate, db: Session = Depends(get_db)):
    db_user = UserModel(
        email=user.email,
        username=user.username,
        hashed_password=pwd_context.hash(user.password)
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

@router.post("/login", response_model=Token)
async def login(email: str, password: str, db: Session = Depends(get_db)):
    user = db.query(UserModel).filter(UserModel.email == email).first()
    if not user or not pwd_context.verify(password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Invalid credentials")
    
    access_token = jwt.encode(
        {"sub": user.email, "exp": datetime.utcnow() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)},
        settings.SECRET_KEY,
        algorithm=settings.ALGORITHM
    )
    return {"access_token": access_token, "token_type": "bearer"}
"""
    
    def _template_python_items_router(self) -> str:
        return """from fastapi import APIRouter, Depends, HTTPException
from app.schemas import Item, ItemCreate
from app.models import Item as ItemModel
from sqlalchemy.orm import Session
from app.database import get_db

router = APIRouter()

@router.post("/", response_model=Item)
async def create_item(item: ItemCreate, db: Session = Depends(get_db)):
    db_item = ItemModel(**item.dict())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item

@router.get("/{item_id}", response_model=Item)
async def get_item(item_id: int, db: Session = Depends(get_db)):
    return db.query(ItemModel).filter(ItemModel.id == item_id).first()

@router.get("/", response_model=list[Item])
async def list_items(skip: int = 0, limit: int = 10, db: Session = Depends(get_db)):
    return db.query(ItemModel).offset(skip).limit(limit).all()

@router.put("/{item_id}", response_model=Item)
async def update_item(item_id: int, item: ItemCreate, db: Session = Depends(get_db)):
    db_item = db.query(ItemModel).filter(ItemModel.id == item_id).first()
    if not db_item:
        raise HTTPException(status_code=404, detail="Item not found")
    for key, value in item.dict().items():
        setattr(db_item, key, value)
    db.commit()
    db.refresh(db_item)
    return db_item

@router.delete("/{item_id}")
async def delete_item(item_id: int, db: Session = Depends(get_db)):
    db.query(ItemModel).filter(ItemModel.id == item_id).delete()
    db.commit()
    return {"message": "Item deleted"}
"""
    
    def _template_python_users_router(self) -> str:
        return """from fastapi import APIRouter, Depends
from app.schemas import User
from app.models import User as UserModel
from sqlalchemy.orm import Session
from app.database import get_db

router = APIRouter()

@router.get("/{user_id}", response_model=User)
async def get_user(user_id: int, db: Session = Depends(get_db)):
    return db.query(UserModel).filter(UserModel.id == user_id).first()

@router.get("/", response_model=list[User])
async def list_users(skip: int = 0, limit: int = 10, db: Session = Depends(get_db)):
    return db.query(UserModel).offset(skip).limit(limit).all()
"""
    
    def _template_python_middleware(self) -> str:
        return """import time
from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
import logging

logger = logging.getLogger(__name__)

async def timing_middleware(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    logger.info(f"{request.method} {request.url.path} - {response.status_code} - {process_time:.3f}s")
    return response
"""
    
    def _template_python_dockerfile(self, config: BackendLanguageConfig) -> str:
        return f"""FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
    
    def _template_python_docker_compose(self, config: BackendLanguageConfig) -> str:
        return """version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
"""
    
    def _template_python_env_example(self) -> str:
        return """DATABASE_URL=postgresql://user:password@localhost/dbname
SECRET_KEY=your-secret-key-here
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
"""
    
    def _template_pytest_ini(self) -> str:
        return """[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
"""
    
    def _template_python_tests(self) -> str:
        return """import pytest
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

def test_read_root():
    response = client.get("/")
    assert response.status_code == 200

def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"
"""
    
    # ============== GO (Gin) ==============
    
    def _generate_go(self, config: BackendLanguageConfig, blueprint: Dict[str, Any]) -> Dict[str, str]:
        """Generate Go Gin backend"""
        files = {}
        
        files["go.mod"] = self._template_go_mod(config)
        files["go.sum"] = "# Go dependencies"
        files["main.go"] = self._template_go_main(config)
        files["config/config.go"] = self._template_go_config()
        files["models/user.go"] = self._template_go_user_model()
        files["models/item.go"] = self._template_go_item_model()
        files["handlers/auth.go"] = self._template_go_auth_handler()
        files["handlers/items.go"] = self._template_go_items_handler()
        files["handlers/users.go"] = self._template_go_users_handler()
        files["middleware/middleware.go"] = self._template_go_middleware()
        files["database/db.go"] = self._template_go_database(config)
        files["Dockerfile"] = self._template_go_dockerfile(config)
        files["docker-compose.yml"] = self._template_go_docker_compose()
        files[".env.example"] = self._template_go_env()
        files["Makefile"] = self._template_go_makefile()
        files["main_test.go"] = self._template_go_tests()
        
        return files
    
    def _template_go_mod(self, config: BackendLanguageConfig) -> str:
        return f"""module {config.project_name.lower().replace(" ", "")}

go 1.21

require (
    github.com/gin-gonic/gin v1.9.1
    github.com/gorm.io/gorm v1.25.5
    github.com/gorm.io/driver/postgres v1.5.6
    github.com/joho/godotenv v1.5.1
    github.com/golang-jwt/jwt/v5 v5.0.0
    golang.org/x/crypto v0.16.0
)
"""
    
    def _template_go_main(self, config: BackendLanguageConfig) -> str:
        return f"""package main

import (
    "fmt"
    "log"
    "github.com/gin-gonic/gin"
    "github.com/joho/godotenv"
    "{config.project_name.lower().replace(" ", "")}/config"
    "{config.project_name.lower().replace(" ", "")}/database"
    "{config.project_name.lower().replace(" ", "")}/handlers"
    "{config.project_name.lower().replace(" ", "")}/middleware"
)

func main() {{
    if err := godotenv.Load(); err != nil {{
        log.Println("No .env file found")
    }}

    db := database.InitDB()
    db.AutoMigrate()

    router := gin.Default()

    // Middleware
    router.Use(middleware.CORSMiddleware())
    router.Use(middleware.LoggingMiddleware())

    // Routes
    router.GET("/", func(c *gin.Context) {{
        c.JSON(200, gin.H{{"message": "{config.project_name}", "version": "{config.version}"}})
    }})

    router.GET("/health", func(c *gin.Context) {{
        c.JSON(200, gin.H{{"status": "ok"}})
    }})

    api := router.Group("/api")
    {{
        auth := api.Group("/auth")
        {{
            auth.POST("/register", handlers.Register)
            auth.POST("/login", handlers.Login)
        }}

        items := api.Group("/items")
        {{
            items.POST("/", handlers.CreateItem)
            items.GET("/", handlers.ListItems)
            items.GET("/:id", handlers.GetItem)
            items.PUT("/:id", handlers.UpdateItem)
            items.DELETE("/:id", handlers.DeleteItem)
        }}

        users := api.Group("/users")
        {{
            users.GET("/", handlers.ListUsers)
            users.GET("/:id", handlers.GetUser)
        }}
    }}

    port := ":8000"
    fmt.Printf("Server running on %s\\n", port)
    router.Run(port)
}}
"""
    
    def _template_go_config(self) -> str:
        return """package config

import (
    "os"
)

type Config struct {
    DatabaseURL     string
    SecretKey       string
    JWTAlgorithm    string
    TokenExpMinutes int
}

func LoadConfig() *Config {
    return &Config{
        DatabaseURL:     os.Getenv("DATABASE_URL"),
        SecretKey:       os.Getenv("SECRET_KEY"),
        JWTAlgorithm:    "HS256",
        TokenExpMinutes: 30,
    }
}
"""
    
    def _template_go_user_model(self) -> str:
        return """package models

import "time"

type User struct {
    ID        uint      `gorm:"primaryKey" json:"id"`
    Email     string    `gorm:"unique" json:"email"`
    Username  string    `gorm:"unique" json:"username"`
    Password  string    `json:"-"`
    IsActive  bool      `json:"is_active"`
    CreatedAt time.Time `json:"created_at"`
    UpdatedAt time.Time `json:"updated_at"`
}
"""
    
    def _template_go_item_model(self) -> str:
        return """package models

import "time"

type Item struct {
    ID          uint      `gorm:"primaryKey" json:"id"`
    Title       string    `json:"title"`
    Description string    `json:"description"`
    OwnerID     uint      `json:"owner_id"`
    CreatedAt   time.Time `json:"created_at"`
    UpdatedAt   time.Time `json:"updated_at"`
}
"""
    
    def _template_go_auth_handler(self) -> str:
        return """package handlers

import (
    "net/http"
    "github.com/gin-gonic/gin"
)

type LoginRequest struct {
    Email    string `json:"email" binding:"required,email"`
    Password string `json:"password" binding:"required"`
}

type RegisterRequest struct {
    Email    string `json:"email" binding:"required,email"`
    Username string `json:"username" binding:"required"`
    Password string `json:"password" binding:"required"`
}

func Register(c *gin.Context) {
    var req RegisterRequest
    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
        return
    }
    
    c.JSON(http.StatusCreated, gin.H{"message": "User registered successfully"})
}

func Login(c *gin.Context) {
    var req LoginRequest
    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
        return
    }
    
    c.JSON(http.StatusOK, gin.H{"token": "jwt_token_here"})
}
"""
    
    def _template_go_items_handler(self) -> str:
        return """package handlers

import (
    "net/http"
    "github.com/gin-gonic/gin"
)

func CreateItem(c *gin.Context) {
    c.JSON(http.StatusCreated, gin.H{"message": "Item created"})
}

func ListItems(c *gin.Context) {
    c.JSON(http.StatusOK, gin.H{"items": []interface{}{}})
}

func GetItem(c *gin.Context) {
    c.JSON(http.StatusOK, gin.H{"id": c.Param("id")})
}

func UpdateItem(c *gin.Context) {
    c.JSON(http.StatusOK, gin.H{"message": "Item updated"})
}

func DeleteItem(c *gin.Context) {
    c.JSON(http.StatusOK, gin.H{"message": "Item deleted"})
}
"""
    
    def _template_go_users_handler(self) -> str:
        return """package handlers

import (
    "net/http"
    "github.com/gin-gonic/gin"
)

func ListUsers(c *gin.Context) {
    c.JSON(http.StatusOK, gin.H{"users": []interface{}{}})
}

func GetUser(c *gin.Context) {
    c.JSON(http.StatusOK, gin.H{"id": c.Param("id")})
}
"""
    
    def _template_go_middleware(self) -> str:
        return """package middleware

import (
    "log"
    "time"
    "github.com/gin-gonic/gin"
)

func CORSMiddleware() gin.HandlerFunc {
    return func(c *gin.Context) {
        c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
        c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
        c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
        
        if c.Request.Method == "OPTIONS" {
            c.AbortWithStatus(204)
            return
        }
        
        c.Next()
    }
}

func LoggingMiddleware() gin.HandlerFunc {
    return func(c *gin.Context) {
        startTime := time.Now()
        c.Next()
        duration := time.Since(startTime)
        log.Printf("%s %s %d %v", c.Request.Method, c.Request.URL.Path, c.Writer.Status(), duration)
    }
}
"""
    
    def _template_go_database(self, config: BackendLanguageConfig) -> str:
        return f"""package database

import (
    "log"
    "os"
    "gorm.io/driver/postgres"
    "gorm.io/gorm"
    "{config.project_name.lower().replace(" ", "")}/models"
)

var DB *gorm.DB

type Database struct {{
    Connection *gorm.DB
}}

func InitDB() *Database {{
    dsn := os.Getenv("DATABASE_URL")
    if dsn == "" {{
        dsn = "host=localhost user=user password=password dbname=dbname port=5432 sslmode=disable"
    }}
    
    db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{{}})
    if err != nil {{
        log.Fatal("Failed to connect to database:", err)
    }}
    
    DB = db
    return &Database{{Connection: db}}
}}

func (d *Database) AutoMigrate() {{
    d.Connection.AutoMigrate(&models.User{{}}, &models.Item{{}})
}}
"""
    
    def _template_go_dockerfile(self, config: BackendLanguageConfig) -> str:
        return f"""FROM golang:1.21 AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /app/app .
EXPOSE 8000

CMD ["/root/app"]
"""
    
    def _template_go_docker_compose(self) -> str:
        return """version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
"""
    
    def _template_go_env(self) -> str:
        return """DATABASE_URL=postgresql://user:password@localhost:5432/dbname
SECRET_KEY=your-secret-key-here
JWT_ALGORITHM=HS256
"""
    
    def _template_go_makefile(self) -> str:
        return """.PHONY: build run test clean

build:
\tgo build -o app .

run:
\tgo run main.go

test:
\tgo test ./...

deps:
\tgo mod download

clean:
\trm -f app
"""
    
    def _template_go_tests(self) -> str:
        return """package main

import (
    "testing"
    "github.com/gin-gonic/gin"
)

func TestMain(t *testing.T) {
    gin.SetMode(gin.TestMode)
    
    // Test cases here
}
"""
    
    # ============== RUST (Actix-web) ==============
    
    def _generate_rust(self, config: BackendLanguageConfig, blueprint: Dict[str, Any]) -> Dict[str, str]:
        """Generate Rust Actix-web backend"""
        files = {}
        
        files["Cargo.toml"] = self._template_rust_cargo_toml(config)
        files["src/main.rs"] = self._template_rust_main(config)
        files["src/config.rs"] = self._template_rust_config()
        files["src/models.rs"] = self._template_rust_models()
        files["src/handlers/mod.rs"] = ""
        files["src/handlers/auth.rs"] = self._template_rust_auth_handler()
        files["src/handlers/items.rs"] = self._template_rust_items_handler()
        files["src/db.rs"] = self._template_rust_database()
        files["Dockerfile"] = self._template_rust_dockerfile(config)
        files["docker-compose.yml"] = self._template_rust_docker_compose()
        files[".env.example"] = self._template_rust_env()
        files["tests/integration_test.rs"] = self._template_rust_tests()
        
        return files
    
    def _template_rust_cargo_toml(self, config: BackendLanguageConfig) -> str:
        return f"""[package]
name = "{config.project_name.lower().replace(" ", "_")}"
version = "{config.version}"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
tokio = {{ version = "1", features = ["full"] }}
sqlx = {{ version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }}
dotenv = "0.15"
jsonwebtoken = "9"
bcrypt = "0.15"
uuid = {{ version = "1.0", features = ["v4", "serde"] }}

[dev-dependencies]
actix-rt = "2"
"""
    
    def _template_rust_main(self, config: BackendLanguageConfig) -> str:
        return f"""use actix_web::{{web, App, HttpServer, HttpResponse}};
use dotenv::dotenv;
use std::env;

mod config;
mod models;
mod handlers;
mod db;

#[actix_web::main]
async fn main() -> std::io::Result<()> {{
    dotenv().ok();
    
    let database_url = env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    
    println!("🚀 Starting {config.project_name} server");
    
    HttpServer::new(|| {{
        App::new()
            .route("/", web::get().to(HttpResponse::Ok))
            .route("/health", web::get().to(|| async {{ HttpResponse::Ok().json("ok") }}))
    }})
    .bind("0.0.0.0:8000")?
    .run()
    .await
}}
"""
    
    def _template_rust_config(self) -> str:
        return """use std::env;

pub struct Config {
    pub database_url: String,
    pub secret_key: String,
    pub jwt_algorithm: String,
}

impl Config {
    pub fn from_env() -> Self {
        Self {
            database_url: env::var("DATABASE_URL").expect("DATABASE_URL not set"),
            secret_key: env::var("SECRET_KEY").unwrap_or_else(|_| "your-secret".to_string()),
            jwt_algorithm: "HS256".to_string(),
        }
    }
}
"""
    
    def _template_rust_models(self) -> str:
        return """use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct User {
    pub id: i32,
    pub email: String,
    pub username: String,
    pub password_hash: String,
    pub is_active: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Item {
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub owner_id: i32,
}

#[derive(Debug, Deserialize)]
pub struct LoginRequest {
    pub email: String,
    pub password: String,
}

#[derive(Debug, Deserialize)]
pub struct RegisterRequest {
    pub email: String,
    pub username: String,
    pub password: String,
}
"""
    
    def _template_rust_auth_handler(self) -> str:
        return """use actix_web::{web, HttpResponse};
use crate::models::{LoginRequest, RegisterRequest};

pub async fn register(req: web::Json<RegisterRequest>) -> HttpResponse {
    HttpResponse::Created().json("User registered")
}

pub async fn login(req: web::Json<LoginRequest>) -> HttpResponse {
    HttpResponse::Ok().json("Login successful")
}
"""
    
    def _template_rust_items_handler(self) -> str:
        return """use actix_web::{web, HttpResponse};

pub async fn create_item() -> HttpResponse {
    HttpResponse::Created().json("Item created")
}

pub async fn list_items() -> HttpResponse {
    HttpResponse::Ok().json(vec![])
}

pub async fn get_item(id: web::Path<i32>) -> HttpResponse {
    HttpResponse::Ok().json(id.into_inner())
}

pub async fn update_item(id: web::Path<i32>) -> HttpResponse {
    HttpResponse::Ok().json("Item updated")
}

pub async fn delete_item(id: web::Path<i32>) -> HttpResponse {
    HttpResponse::Ok().json("Item deleted")
}
"""
    
    def _template_rust_database(self) -> str:
        return """use sqlx::postgres::PgPool;

pub struct Database {
    pub pool: PgPool,
}

impl Database {
    pub async fn new(database_url: &str) -> Result<Self, sqlx::Error> {
        let pool = PgPool::connect(database_url).await?;
        Ok(Self { pool })
    }
}
"""
    
    def _template_rust_dockerfile(self, config: BackendLanguageConfig) -> str:
        return f"""FROM rust:latest AS builder

WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/{config.project_name.lower().replace(" ", "_")} /usr/local/bin/app

EXPOSE 8000
CMD ["app"]
"""
    
    def _template_rust_docker_compose(self) -> str:
        return """version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"

volumes:
  postgres_data:
"""
    
    def _template_rust_env(self) -> str:
        return """DATABASE_URL=postgresql://user:password@localhost:5432/dbname
SECRET_KEY=your-secret-key-here
"""
    
    def _template_rust_tests(self) -> str:
        return """#[cfg(test)]
mod tests {
    #[test]
    fn test_example() {
        assert_eq!(2 + 2, 4);
    }
}
"""
    
    # ============== JAVA (Spring Boot) ==============
    
    def _generate_java(self, config: BackendLanguageConfig, blueprint: Dict[str, Any]) -> Dict[str, str]:
        """Generate Java Spring Boot backend"""
        files = {}
        
        files["pom.xml"] = self._template_java_pom(config)
        files["src/main/java/Application.java"] = self._template_java_main(config)
        files["src/main/java/config/SecurityConfig.java"] = self._template_java_security_config()
        files["src/main/java/models/User.java"] = self._template_java_user_model()
        files["src/main/java/models/Item.java"] = self._template_java_item_model()
        files["src/main/java/repositories/UserRepository.java"] = self._template_java_user_repo()
        files["src/main/java/repositories/ItemRepository.java"] = self._template_java_item_repo()
        files["src/main/java/controllers/AuthController.java"] = self._template_java_auth_controller()
        files["src/main/java/controllers/ItemController.java"] = self._template_java_item_controller()
        files["src/main/java/services/UserService.java"] = self._template_java_user_service()
        files["src/main/resources/application.yml"] = self._template_java_application_yml(config)
        files["Dockerfile"] = self._template_java_dockerfile(config)
        files["docker-compose.yml"] = self._template_java_docker_compose()
        files[".env.example"] = self._template_java_env()
        
        return files
    
    def _template_java_pom(self, config: BackendLanguageConfig) -> str:
        return f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.gaaius</groupId>
    <artifactId>{config.project_name.lower().replace(" ", "")}</artifactId>
    <version>{config.version}</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.0</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.11.5</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""
    
    def _template_java_main(self, config: BackendLanguageConfig) -> str:
        return """package com.gaaius;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
"""
    
    def _template_java_security_config(self) -> str:
        return """package com.gaaius.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.SecurityFilterChain;

@Configuration
public class SecurityConfig {
    
    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http
            .csrf().disable()
            .authorizeRequests()
            .anyRequest().permitAll();
        return http.build();
    }
}
"""
    
    def _template_java_user_model(self) -> str:
        return """package com.gaaius.models;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

@Entity
@Table(name = "users")
@Data
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(unique = true)
    private String email;
    
    @Column(unique = true)
    private String username;
    
    private String passwordHash;
    private boolean isActive;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
"""
    
    def _template_java_item_model(self) -> str:
        return """package com.gaaius.models;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

@Entity
@Table(name = "items")
@Data
public class Item {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    private String title;
    private String description;
    private Long ownerId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
"""
    
    def _template_java_user_repo(self) -> str:
        return """package com.gaaius.repositories;

import com.gaaius.models.User;
import org.springframework.data.jpa.repository.JpaRepository;

public interface UserRepository extends JpaRepository<User, Long> {
    User findByEmail(String email);
    User findByUsername(String username);
}
"""
    
    def _template_java_item_repo(self) -> str:
        return """package com.gaaius.repositories;

import com.gaaius.models.Item;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.List;

public interface ItemRepository extends JpaRepository<Item, Long> {
    List<Item> findByOwnerId(Long ownerId);
}
"""
    
    def _template_java_auth_controller(self) -> str:
        return """package com.gaaius.controllers;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;

@RestController
@RequestMapping("/api/auth")
public class AuthController {
    
    @PostMapping("/register")
    public ResponseEntity<?> register(@RequestBody Map<String, String> body) {
        return ResponseEntity.ok("User registered");
    }
    
    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody Map<String, String> body) {
        return ResponseEntity.ok("Login successful");
    }
}
"""
    
    def _template_java_item_controller(self) -> str:
        return """package com.gaaius.controllers;

import com.gaaius.models.Item;
import com.gaaius.repositories.ItemRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import java.util.List;

@RestController
@RequestMapping("/api/items")
public class ItemController {
    
    @Autowired
    private ItemRepository itemRepository;
    
    @PostMapping
    public ResponseEntity<Item> createItem(@RequestBody Item item) {
        return ResponseEntity.ok(itemRepository.save(item));
    }
    
    @GetMapping
    public ResponseEntity<List<Item>> listItems() {
        return ResponseEntity.ok(itemRepository.findAll());
    }
    
    @GetMapping("/{id}")
    public ResponseEntity<Item> getItem(@PathVariable Long id) {
        return ResponseEntity.ok(itemRepository.findById(id).orElse(null));
    }
}
"""
    
    def _template_java_user_service(self) -> str:
        return """package com.gaaius.services;

import com.gaaius.models.User;
import com.gaaius.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class UserService {
    
    @Autowired
    private UserRepository userRepository;
    
    public User findByEmail(String email) {
        return userRepository.findByEmail(email);
    }
    
    public List<User> findAll() {
        return userRepository.findAll();
    }
}
"""
    
    def _template_java_application_yml(self, config: BackendLanguageConfig) -> str:
        return f"""spring:
  application:
    name: {config.project_name.lower().replace(" ", "-")}
  
  datasource:
    url: jdbc:postgresql://localhost:5432/dbname
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  
server:
  port: 8000
  servlet:
    context-path: /
"""
    
    def _template_java_dockerfile(self, config: BackendLanguageConfig) -> str:
        return f"""FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8000
ENTRYPOINT ["java", "-jar", "app.jar"]
"""
    
    def _template_java_docker_compose(self) -> str:
        return """version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dbname
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
"""
    
    def _template_java_env(self) -> str:
        return """SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/dbname
SPRING_DATASOURCE_USERNAME=user
SPRING_DATASOURCE_PASSWORD=password
"""
    
    # ============== C# (ASP.NET Core) ==============
    
    def _generate_csharp(self, config: BackendLanguageConfig, blueprint: Dict[str, Any]) -> Dict[str, str]:
        """Generate C# ASP.NET Core backend"""
        files = {}
        
        files[f"{config.project_name}.csproj"] = self._template_csharp_csproj(config)
        files["Program.cs"] = self._template_csharp_program(config)
        files["appsettings.json"] = self._template_csharp_settings(config)
        files["Models/User.cs"] = self._template_csharp_user_model()
        files["Models/Item.cs"] = self._template_csharp_item_model()
        files["Data/AppDbContext.cs"] = self._template_csharp_dbcontext()
        files["Controllers/AuthController.cs"] = self._template_csharp_auth_controller()
        files["Controllers/ItemsController.cs"] = self._template_csharp_items_controller()
        files["Services/AuthService.cs"] = self._template_csharp_auth_service()
        files["Dockerfile"] = self._template_csharp_dockerfile(config)
        files["docker-compose.yml"] = self._template_csharp_docker_compose()
        files[".env.example"] = self._template_csharp_env()
        
        return files
    
    def _template_csharp_csproj(self, config: BackendLanguageConfig) -> str:
        return f"""<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>{config.project_name.replace(" ", "")}</AssemblyName>
    <RootNamespace>{config.project_name.replace(" ", "")}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Npgsql" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.6" />
  </ItemGroup>

</Project>
"""
    
    def _template_csharp_program(self, config: BackendLanguageConfig) -> str:
        return f"""var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddCors(options =>
{{
    options.AddPolicy("AllowAll",
        policy => policy
            .AllowAnyOrigin()
            .AllowAnyMethod()
            .AllowAnyHeader());
}});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{{
    app.UseSwagger();
    app.UseSwaggerUI();
}}

app.UseHttpsRedirection();
app.UseCors("AllowAll");
app.UseAuthorization();
app.MapControllers();

app.Run();
"""
    
    def _template_csharp_settings(self, config: BackendLanguageConfig) -> str:
        return json.dumps({
            "Logging": {
                "LogLevel": {
                    "Default": "Information",
                    "Microsoft.AspNetCore": "Warning"
                }
            },
            "AllowedHosts": "*",
            "ConnectionStrings": {
                "DefaultConnection": "Host=localhost;Port=5432;Database=dbname;Username=user;Password=password"
            }
        }, indent=2)
    
    def _template_csharp_user_model(self) -> str:
        return """namespace GAAIUS.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Email { get; set; } = string.Empty;
        public string Username { get; set; } = string.Empty;
        public string PasswordHash { get; set; } = string.Empty;
        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
"""
    
    def _template_csharp_item_model(self) -> str:
        return """namespace GAAIUS.Models
{
    public class Item
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        public int OwnerId { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
"""
    
    def _template_csharp_dbcontext(self) -> str:
        return """using Microsoft.EntityFrameworkCore;
using GAAIUS.Models;

namespace GAAIUS.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<User> Users { get; set; }
        public DbSet<Item> Items { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            
            modelBuilder.Entity<User>()
                .HasIndex(u => u.Email)
                .IsUnique();
        }
    }
}
"""
    
    def _template_csharp_auth_controller(self) -> str:
        return """using Microsoft.AspNetCore.Mvc;

namespace GAAIUS.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AuthController : ControllerBase
    {
        [HttpPost("register")]
        public ActionResult<string> Register([FromBody] RegisterRequest request)
        {
            return Ok("User registered successfully");
        }

        [HttpPost("login")]
        public ActionResult<string> Login([FromBody] LoginRequest request)
        {
            return Ok("Login successful");
        }
    }

    public record RegisterRequest(string Email, string Username, string Password);
    public record LoginRequest(string Email, string Password);
}
"""
    
    def _template_csharp_items_controller(self) -> str:
        return """using Microsoft.AspNetCore.Mvc;
using GAAIUS.Models;

namespace GAAIUS.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ItemsController : ControllerBase
    {
        [HttpPost]
        public ActionResult<Item> CreateItem([FromBody] Item item)
        {
            return CreatedAtAction("GetItem", new { id = item.Id }, item);
        }

        [HttpGet("{id}")]
        public ActionResult<Item> GetItem(int id)
        {
            return Ok(new Item { Id = id });
        }

        [HttpGet]
        public ActionResult<IEnumerable<Item>> ListItems()
        {
            return Ok(new List<Item>());
        }
    }
}
"""
    
    def _template_csharp_auth_service(self) -> str:
        return """using GAAIUS.Models;

namespace GAAIUS.Services
{
    public interface IAuthService
    {
        Task<User?> Register(string email, string username, string password);
        Task<string?> Login(string email, string password);
    }

    public class AuthService : IAuthService
    {
        public Task<User?> Register(string email, string username, string password)
        {
            return Task.FromResult<User?>(null);
        }

        public Task<string?> Login(string email, string password)
        {
            return Task.FromResult<string?>(null);
        }
    }
}
"""
    
    def _template_csharp_dockerfile(self, config: BackendLanguageConfig) -> str:
        return f"""FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder

WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app
COPY --from=builder /app/out .

EXPOSE 8000
ENV ASPNETCORE_URLS=http://+:8000
ENTRYPOINT ["dotnet", "{config.project_name.replace(" ", "")}.dll"]
"""
    
    def _template_csharp_docker_compose(self) -> str:
        return """version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=dbname;Username=user;Password=password"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
"""
    
    def _template_csharp_env(self) -> str:
        return """ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=dbname;Username=user;Password=password
"""
    
    # ============== PHP (Laravel) ==============
    
    def _generate_php(self, config: BackendLanguageConfig, blueprint: Dict[str, Any]) -> Dict[str, str]:
        """Generate PHP Laravel backend"""
        files = {}
        
        files["composer.json"] = self._template_php_composer(config)
        files[".env.example"] = self._template_php_env()
        files["routes/api.php"] = self._template_php_routes()
        files["app/Models/User.php"] = self._template_php_user_model()
        files["app/Models/Item.php"] = self._template_php_item_model()
        files["app/Http/Controllers/AuthController.php"] = self._template_php_auth_controller()
        files["app/Http/Controllers/ItemController.php"] = self._template_php_item_controller()
        files["database/migrations/users_table.php"] = self._template_php_users_migration()
        files["database/migrations/items_table.php"] = self._template_php_items_migration()
        files["Dockerfile"] = self._template_php_dockerfile(config)
        files["docker-compose.yml"] = self._template_php_docker_compose()
        
        return files
    
    def _template_php_composer(self, config: BackendLanguageConfig) -> str:
        return f"""{{
    "name": "{config.project_name.lower().replace(' ', '/')}",
    "description": "{config.project_name} API",
    "type": "project",
    "require": {{
        "php": "^8.2",
        "laravel/framework": "^11.0",
        "laravel/passport": "^2.0"
    }},
    "require-dev": {{
        "phpunit/phpunit": "^10.0"
    }},
    "autoload": {{
        "psr-4": {{
            "App\\\\": "app/",
            "Database\\\\Factories\\\\": "database/factories/",
            "Database\\\\Seeders\\\\": "database/seeders/"
        }}
    }}
}}
"""
    
    def _template_php_env(self) -> str:
        return """APP_NAME="GAAIUS App"
APP_KEY=base64:
APP_DEBUG=true
APP_URL=http://localhost:8000

DB_CONNECTION=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=dbname
DB_USERNAME=user
DB_PASSWORD=password

JWT_SECRET=
"""
    
    def _template_php_routes(self) -> str:
        return """<?php

use Illuminate\\Routing\\Router;

Route::prefix('api')->group(function () {
    Route::post('auth/register', 'AuthController@register');
    Route::post('auth/login', 'AuthController@login');

    Route::middleware('auth:api')->group(function () {
        Route::resource('items', 'ItemController');
        Route::resource('users', 'UserController');
    });
});
"""
    
    def _template_php_user_model(self) -> str:
        return """<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Model;

class User extends Model
{
    protected $fillable = ['email', 'username', 'password'];
    protected $hidden = ['password'];
}
"""
    
    def _template_php_item_model(self) -> str:
        return """<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Model;

class Item extends Model
{
    protected $fillable = ['title', 'description', 'owner_id'];
}
"""
    
    def _template_php_auth_controller(self) -> str:
        return """<?php

namespace App\\Http\\Controllers;

use Illuminate\\Http\\Request;
use App\\Models\\User;

class AuthController extends Controller
{
    public function register(Request $request)
    {
        return response()->json(['message' => 'User registered'], 201);
    }

    public function login(Request $request)
    {
        return response()->json(['message' => 'Login successful']);
    }
}
"""
    
    def _template_php_item_controller(self) -> str:
        return """<?php

namespace App\\Http\\Controllers;

use App\\Models\\Item;
use Illuminate\\Http\\Request;

class ItemController extends Controller
{
    public function index()
    {
        return Item::all();
    }

    public function store(Request $request)
    {
        return Item::create($request->all());
    }

    public function show(Item $item)
    {
        return $item;
    }

    public function update(Request $request, Item $item)
    {
        $item->update($request->all());
        return $item;
    }

    public function destroy(Item $item)
    {
        $item->delete();
        return response()->json(['message' => 'Item deleted']);
    }
}
"""
    
    def _template_php_users_migration(self) -> str:
        return """<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('email')->unique();
            $table->string('username')->unique();
            $table->string('password');
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });
    }
};
"""
    
    def _template_php_items_migration(self) -> str:
        return """<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('items', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->text('description')->nullable();
            $table->unsignedBigInteger('owner_id');
            $table->timestamps();
        });
    }
};
"""
    
    def _template_php_dockerfile(self, config: BackendLanguageConfig) -> str:
        return f"""FROM php:8.2-fpm

WORKDIR /app

RUN apt-get update && apt-get install -y \\
    libpq-dev \\
    && docker-php-ext-install pdo pdo_pgsql

COPY composer.json composer.lock ./
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \\
    && composer install

COPY . .

RUN chown -R www-data:www-data /app

EXPOSE 8000
CMD ["php", "-S", "0.0.0.0:8000"]
"""
    
    def _template_php_docker_compose(self) -> str:
        return """version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=dbname
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
"""
