import asyncio
import os
from pathlib import Path

print('\n=== SMOKE TESTS for backend ===')

# Test specs validation
try:
    from specs import validate_product_spec, validate_design_spec
    print('\n-- specs module imported')
except Exception as e:
    print('Failed to import specs:', e)
    raise

valid_spec = {
    'name': 'TestApp',
    'description': 'A small test app',
    'features': [
        {'id': 'f1', 'name': 'FeatureOne', 'description': 'First feature'}
    ]
}

invalid_spec = {
    'description': 'Missing name'
}

print('Valid spec ->', validate_product_spec(valid_spec))
print('Invalid spec ->', validate_product_spec(invalid_spec))

# Test file generator
try:
    from file_generator import generate_project_files
    print('\n-- file_generator module imported')
except Exception as e:
    print('Failed to import file_generator:', e)
    raise

orchestrator_outputs = {
    'frontend_engineer': {
        'code': 'FILE: frontend/src/pages/index.tsx\n```tsx\nexport default function Home(){ return <h1>Hello</h1> }\n```'
    },
    'backend_engineer': {
        'code': 'FILE: server.js\n```js\nconsole.log("server")\n```'
    },
    'product_manager': {
        'name': 'TestApp',
        'description': 'Generated by smoke test'
    },
    'ui_designer': {
        'name': 'TestDesign',
        'pages': []
    }
}

async def run_gen():
    res = await generate_project_files('SmokeTestProject', orchestrator_outputs, output_dir='./generated_projects_test')
    print('\nGeneration result:')
    print(res)

    out_dir = Path('./generated_projects_test/SmokeTestProject')
    print('\nFiles created in', out_dir)
    for p in sorted([str(p.relative_to(out_dir)) for p in out_dir.rglob('*') if p.is_file()]):
        print(' -', p)

if __name__ == '__main__':
    asyncio.run(run_gen())
