import React, { FC } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import MainLayout from '@/components/layouts/MainLayout';

/**
 * Account Page
 * Page for Account
 */
const AccountPage: FC = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Account - {process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Account page" />
      </Head>
      <MainLayout>
        <main>
          <h1>Account</h1>
          <p>Welcome to Account</p>
        </main>
      </MainLayout>
    </>
  );
};

export default AccountPage;

// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation