import React, { FC } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import MainLayout from '@/components/layouts/MainLayout';

/**
 * Cart Page
 * Page for Cart
 */
const CartPage: FC = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Cart - {process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Cart page" />
      </Head>
      <MainLayout>
        <main>
          <h1>Cart</h1>
          <p>Welcome to Cart</p>
        </main>
      </MainLayout>
    </>
  );
};

export default CartPage;

// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation