import React, { FC } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import MainLayout from '@/components/layouts/MainLayout';

/**
 * Checkout Page
 * Page for Checkout
 */
const CheckoutPage: FC = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Checkout - {process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Checkout page" />
      </Head>
      <MainLayout>
        <main>
          <h1>Checkout</h1>
          <p>Welcome to Checkout</p>
        </main>
      </MainLayout>
    </>
  );
};

export default CheckoutPage;

// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation