import React, { FC } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import MainLayout from '@/components/layouts/MainLayout';

/**
 * Index Page
 * Page for Index
 */
const IndexPage: FC = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Index - {process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Index page" />
      </Head>
      <MainLayout>
        <main>
          <h1>Index</h1>
          <p>Welcome to Index</p>
        </main>
      </MainLayout>
    </>
  );
};

export default IndexPage;

// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation