import React, { FC } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import MainLayout from '@/components/layouts/MainLayout';

/**
 * Product Detail Page
 * Page for Product Detail
 */
const Product DetailPage: FC = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Product Detail - {process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Product Detail page" />
      </Head>
      <MainLayout>
        <main>
          <h1>Product Detail</h1>
          <p>Welcome to Product Detail</p>
        </main>
      </MainLayout>
    </>
  );
};

export default Product DetailPage;

// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation
// Page implementation